ruta_archivos: "/Volumes/Resources/Develop/SmartBots/Santa_Elena/Contabilidad/Por Hacer"

# Configuración para obtener archivos desde Google Drive
google_drive_source:
  carpeta_por_hacer: "SantaElena/IConstruye/Por Hacer"
  carpeta_procesados: "SantaElena/IConstruye/Procesados"
  destino_local: "/Volumes/Resources/Develop/SmartBots/Santa_Elena/Contabilidad/Por Hacer"

web_scraping:
  login_url: "https://cl.iconstruye.com/loginsso.aspx?hsCtaTracking=c5739d9b-1567-4a49-90d4-9e8e1701f105%7Cc9ffe135-4402-4101-a071-33ca6e5227d4"
  usuario: "ltarrillo@santaelena.com"
  clave: "Lt*.2020"
  chromedriver_path: "/Volumes/Resources/Develop/SmartBots/Santa_Elena/Contabilidad/ChromeDriver/chromedriver" # Ruta de ChromeDriver
  carpeta_descargas: "/Volumes/Resources/Develop/SmartBots/Santa_Elena/Contabilidad/Descargas" # Ahora será la carpeta de destino directa
  areas_correos: "/Volumes/Resources/Develop/SmartBots/Santa_Elena/Contabilidad/Contabilidad IConstruye/data/configuracion_correo.xlsx"
  plantilla_correo: "/Volumes/Resources/Develop/SmartBots/Santa_Elena/Contabilidad/Contabilidad IConstruye/src/templates/plantilla.html"

google:
  cuenta: facturasproveedores@santaelena.com
  clave: Fe*.2020

correo:
  destinatario_informe: h.buddenberg@gmail.com #goliverz1995@gmail.com, ltarrillo@santaelena.com
  cc: hans.buddenberg@smart-bots.cl
  cco: h.buddenberg@gmail.com

informes:
  directorio_local: "/Volumes/Resources/Develop/SmartBots/Santa_Elena/Contabilidad/Contabilidad IConstruye/informes"
  nombre_archivo: "informe_resumen_{area}_{fecha}.xlsx"

procesados:
  carpeta_listos: "/Volumes/Resources/Develop/SmartBots/Santa_Elena/Contabilidad/Listos"

google_drive:
  carpeta_destino: "SantaElena/IConstruye/Facturas"
